version: '3'
services:
  webapp:
    container_name: docker_test
    build: src/
    image: andrey1981spb/docker_test
    depends_on:
      - psql
  psql:
    container_name: docker_db
    build: database/
    image: andrey1981spb/docker_db
    ports:
      - 5432:5432
