version: '3'

services:
  webapp:
    container_name: users
    build:
      context: .
    image: andrey1981spb/users
    restart: always
    ports:
      - 8080:50000

  psql2:
    container_name: users_db
    build:
      context: ./database
    image: andrey1981spb/users_db
    restart: always







