version: '3'

services:
  webapp:
    container_name: docker_test
    build: src/
    image: andrey1981spb/docker_test
    volumes:
      - "/var/run/postgresql/.s.PGSQL.5432:/var/run/postgresql/.s.PGSQL.5432"
      - "/var/lib/pgsql/data:/var/lib/pgsql/data"
      - "/var/run/postgresql/.s.PGSQL.5432:/tmp/.s.PGSQL.5432"
    depends_on:
      - psql
    ports:
    - 8080:50000
  psql:
    container_name: docker_db
    build: database/
    image: andrey1981spb/docker_db
    ports:
      - 5432:5432


