version: '3'
services:
  maven:
    container_name: maven-container
    build:
      context: .
      dockerfile: Dockerfile_tk

  tomcat:
    container_name: tomcat-container
    build:
      context: .
      dockerfile: Dockerfile_tk